export enum CustomNodes {
    BinaryExpressionFunctionNode,
    BlockStatementControlFlowReplacerNode,
    CallExpressionControlFlowStorageCallNode,
    CallExpressionFunctionNode,
    ControlFlowStorageNode,
    ConsoleOutputDisableExpressionNode,
    DebugProtectionFunctionCallNode,
    DebugProtectionFunctionIntervalNode,
    DebugProtectionFunctionNode,
    DomainLockNode,
    ExpressionWithOperatorControlFlowStorageCallNode,
    LogicalExpressionFunctionNode,
    NodeCallsControllerFunctionNode,
    SelfDefendingUnicodeNode,
    StringArrayCallsWrapper,
    StringArrayNode,
    StringArrayRotateFunctionNode
}
