export const ServiceIdentifiers: any = {
    'Factory<ICalleeDataExtractor>': Symbol('Factory<ICalleeDataExtractor>'),
    'Factory<IControlFlowReplacer>': Symbol('Factory<IControlFlowReplacer>'),
    'Factory<ICustomNode>': Symbol('Factory<ICustomNode>'),
    'Factory<ICustomNodeGroup>': Symbol('Factory<ICustomNodeGroup>'),
    'Factory<INodeTransformer[]>': Symbol('Factory<INodeTransformer[]>'),
    'Factory<IObfuscationResult>': Symbol('Factory<IObfuscationResult>'),
    'Factory<IObfuscatorReplacer>': Symbol('Factory<IObfuscatorReplacer>'),
    'Factory<IStorage<ICustomNode>>': Symbol('Factory<IStorage<ICustomNode>>'),
    ICalleeDataExtractor: Symbol('ICalleeDataExtractor'),
    ICustomNode: Symbol('ICustomNode'),
    ICustomNodeGroup: Symbol('ICustomNodeGroup'),
    IControlFlowReplacer: Symbol('IControlFlowReplacer'),
    IJavaScriptObfuscator: Symbol('IJavaScriptObfuscator'),
    INodeTransformer: Symbol('INodeTransformer'),
    IObfuscationEventEmitter: Symbol('IObfuscationEventEmitter'),
    IObfuscationResult: Symbol('IObfuscationResult'),
    IObfuscator: Symbol('IObfuscator'),
    IOptions: Symbol('IOptions'),
    IObfuscatorReplacer: Symbol('IObfuscatorReplacer'),
    ISourceMapCorrector: Symbol('ISourceMapCorrector'),
    IStackTraceAnalyzer: Symbol('IStackTraceAnalyzer'),
    'IStorage<ICustomNode>': Symbol('IStorage<ICustomNode>'),
    'IStorage<ICustomNodeGroup>': Symbol('IStorage<ICustomNodeGroup>'),
    'IStorage<string>': Symbol('IStorage<string>')
};
