export const ServiceIdentifiers: any = {
    Factory__ICalleeDataExtractor: Symbol('Factory<ICalleeDataExtractor>'),
    Factory__IControlFlowReplacer: Symbol('Factory<IControlFlowReplacer>'),
    Factory__ICustomNode: Symbol('Factory<ICustomNode>'),
    Factory__ICustomNodeGroup: Symbol('Factory<ICustomNodeGroup>'),
    Factory__INodeTransformer: Symbol('Factory<INodeTransformer[]>'),
    Factory__IObfuscationResult: Symbol('Factory<IObfuscationResult>'),
    Factory__IObfuscatingReplacer: Symbol('Factory<IObfuscatingReplacer>'),
    Factory__TControlFlowStorage: Symbol('Factory<TControlFlowStorage>'),
    ICalleeDataExtractor: Symbol('ICalleeDataExtractor'),
    ICustomNodeGroup: Symbol('ICustomNodeGroup'),
    IControlFlowReplacer: Symbol('IControlFlowReplacer'),
    IDeadCodeInjectionReplacer: Symbol('IDeadCodeInjectionReplacer'),
    IJavaScriptObfuscator: Symbol('IJavaScriptObfuscator'),
    INodeTransformer: Symbol('INodeTransformer'),
    IObfuscationEventEmitter: Symbol('IObfuscationEventEmitter'),
    IObfuscationResult: Symbol('IObfuscationResult'),
    IObfuscator: Symbol('IObfuscator'),
    IOptions: Symbol('IOptions'),
    IObfuscatingReplacer: Symbol('IObfuscatingReplacer'),
    ISourceMapCorrector: Symbol('ISourceMapCorrector'),
    IStackTraceAnalyzer: Symbol('IStackTraceAnalyzer'),
    Newable__ICustomNode: Symbol('Newable<ICustomNode>'),
    Newable__TControlFlowStorage: Symbol('Newable<TControlFlowStorage>'),
    TCustomNodeGroupStorage: Symbol('TCustomNodeGroupStorage'),
    TStringArrayStorage: Symbol('TStringArrayStorage')
};
