export enum NodeTransformer {
    AstToEvalCallExpressionTransformer = 'AstToEvalCallExpressionTransformer',
    BlockStatementControlFlowTransformer = 'BlockStatementControlFlowTransformer',
    ClassDeclarationTransformer = 'ClassDeclarationTransformer',
    CommentsTransformer = 'CommentsTransformer',
    DeadCodeInjectionTransformer = 'DeadCodeInjectionTransformer',
    EvalCallExpressionToAstTransformer = 'EvalCallExpressionToAstTransformer',
    FunctionControlFlowTransformer = 'FunctionControlFlowTransformer',
    CatchClauseTransformer = 'CatchClauseTransformer',
    FunctionDeclarationTransformer = 'FunctionDeclarationTransformer',
    FunctionTransformer = 'FunctionTransformer',
    LabeledStatementTransformer = 'LabeledStatementTransformer',
    LiteralTransformer = 'LiteralTransformer',
    MemberExpressionTransformer = 'MemberExpressionTransformer',
    MethodDefinitionTransformer = 'MethodDefinitionTransformer',
    ObfuscatingGuardsTransformer = 'ObfuscatingGuardsTransformer',
    ObjectExpressionKeysTransformer = 'ObjectExpressionKeysTransformer',
    ObjectExpressionTransformer = 'ObjectExpressionTransformer',
    ParentificationTransformer = 'ParentificationTransformer',
    TemplateLiteralTransformer = 'TemplateLiteralTransformer',
    VariableDeclarationTransformer = 'VariableDeclarationTransformer'
}
