export enum NodeTransformer {
    BlockStatementControlFlowTransformer = 'BlockStatementControlFlowTransformer',
    CommentsTransformer = 'CommentsTransformer',
    CustomCodeHelpersTransformer = 'CustomCodeHelpersTransformer',
    DeadCodeInjectionTransformer = 'DeadCodeInjectionTransformer',
    EvalCallExpressionTransformer = 'EvalCallExpressionTransformer',
    FunctionControlFlowTransformer = 'FunctionControlFlowTransformer',
    LabeledStatementTransformer = 'LabeledStatementTransformer',
    LiteralTransformer = 'LiteralTransformer',
    MemberExpressionTransformer = 'MemberExpressionTransformer',
    MetadataTransformer = 'MetadataTransformer',
    MethodDefinitionTransformer = 'MethodDefinitionTransformer',
    ObfuscatingGuardsTransformer = 'ObfuscatingGuardsTransformer',
    ObjectExpressionKeysTransformer = 'ObjectExpressionKeysTransformer',
    ObjectExpressionTransformer = 'ObjectExpressionTransformer',
    ParentificationTransformer = 'ParentificationTransformer',
    ScopeIdentifiersTransformer = 'ScopeIdentifiersTransformer',
    SplitStringTransformer = 'SplitStringTransformer',
    TemplateLiteralTransformer = 'TemplateLiteralTransformer',
    VariablePreserveTransformer = 'VariablePreserveTransformer'
}
