#!/bin/bash

npm run test:removeTmpDir &&
npm run test:compile &&
node test-tmp/test/dev/dev.js &&
$(npm bin)/istanbul cover $(npm bin)/_mocha -- test-tmp/test/index.spec.js &&
npm run test:removeTmpDir