#!/bin/bash

npm run test:removeTmpDir &&
npm run test:compile &&
$(npm bin)/istanbul cover $(npm bin)/_mocha -- test-tmp/test/index.spec.js --report lcovonly &&
cat ./coverage/lcov.info | $(npm bin)/coveralls &&
npm run test:removeTmpDir