#!/bin/bash

yarn run test:removeTmpDir &&
yarn run test:compile &&
$(yarn bin)/nyc --reporter lcovonly $(yarn bin)/mocha -- test-tmp/test/index.spec.js &&
cat ./coverage/lcov.info | $(yarn bin)/coveralls &&
yarn run test:removeTmpDir